version: '3'

services:
  zookeeper:
    image: zookeeper
    restart: always
    container_name: decaf_zookeeper_service
    ports:
      - 2181:2181
  mysql:
    image: mysql:5.6
    restart: always
    container_name: decaf_mysql_service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword@mysql
    volumes:
      - ./conf-mysql-db:/var/lib/mysql
      - ./xxl-conf/doc/db:/docker-entrypoint-initdb.d
  admin:
    image: openweb/oracle-tomcat:7-jre8
    container_name: decaf_tomcat_service
    ports:
      - "8081:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    depends_on:
      - mysql
      - zookeeper